name: stormberry_example
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  args: ^2.0.0
  stormberry: ^0.11.0
  dotenv: ^4.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  build_runner: 
