name: hospitals
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dotenv: ^4.0.1
  fast_csv: ^0.1.44
  fpdart: ^0.4.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
